.ddev/config.yaml

Issue 104
Changed Nqinx to Apache
Changed Mariadb to Mysql

Update config.yaml for ddev optimalization

---

.gitignore.example
config/general.php

Don't transform gifs

---

templates/_site/_searchResults.twig

Improve the out of the box search results, only actual content pages should be searched

Improve the out of the box search results

---

templates/_site/_snippet/_content/_blocks/_image.twig

Fixes #109
Now the sizes are adjusted in function of the width of the image. This gives better performance and quality.

Optimize the _image.twig template

---

config/project/matrixBlockTypes/callToAction--7b5ab248-6255-4b42-88bc-80c1dee62b20.yaml
config/project/matrixBlockTypes/customTable--f2d33237-c7de-4590-9683-7efe6594ebbd.yaml
config/project/matrixBlockTypes/form--f3211a4e-d5f8-4514-a372-c5b8cfc2c44a.yaml
config/project/matrixBlockTypes/image--0396f80c-a192-4beb-a6e7-075075cf0f70.yaml
config/project/matrixBlockTypes/quote--7256a782-20ff-4771-9d85-ed3f49e13ef4.yaml
config/project/matrixBlockTypes/textImage--d86336d6-7efa-44f9-9a10-8619c79beeca.yaml
config/project/matrixBlockTypes/textTwoColumns--1e4267e1-8d5f-4312-8458-86b19bc17d74.yaml
config/project/matrixBlockTypes/textVideo--95920915-f806-4fbc-9c22-979ec9085fe8.yaml
config/project/project.yaml
config/project/superTableBlockTypes/175c42fc-da01-4ded-8cf6-ca10dd488101.yaml
config/project/superTableBlockTypes/284daef2-f89a-4911-9fa6-7176a9a9c2e8.yaml
config/project/superTableBlockTypes/9992e38a-47e2-43e6-93a9-3bc09a42c504.yaml

Set full to default in the Image width option as part of the content builder

---

tailoff/css/site/components/ajax-search.css
tailoff/css/site/components/autocomplete.css
tailoff/css/site/components/filter-button.css
tailoff/css/site/components/flyout.css
tailoff/css/site/components/glide.css
tailoff/css/site/components/link.css
tailoff/css/site/components/loader.css
tailoff/css/site/components/masonry.css
tailoff/css/site/components/modal.css
tailoff/css/site/components/range-slider.css
tailoff/css/site/components/search.css
tailoff/css/site/components/section.css
tailoff/css/site/components/site.css
tailoff/css/site/components/sticky-header.css
tailoff/css/site/components/table.css
tailoff/css/site/components/tabs.css
tailoff/css/site/components/video-bg.css
tailoff/css/site/utilities/hover-underline.css

Fixes #108
Removed all layers in components to prevent purging.

Cleanup css files

---

tailoff/js/components/chip.component.ts
tailoff/js/components/indeterminateChecks.component.ts
templates/jsPlugins/chipFilter.twig

Combine IndeterminateChecks and ChipComponent

---

config/project/ckeditor/configs/25f93ead-d3f6-4049-ba98-6378754f4289.yaml
config/project/ckeditor/configs/7d23b02c-ad1d-44a8-9751-35fbdcc38963.yaml
config/project/project.yaml
package.json
tailoff/css/site/base/icon.css
tailoff/css/site/base/mixins.css
tailoff/css/site/ckeditor.css
tailoff/css/site/main.css
tailoff/js/site.ts
vite-ckeditor.config.js

Fixes #111
This gives the optiion to style elements in the ckeditor like they will appear in the website. 
Like UL en OL and Link

Improve backend editor with CKEditor custom styles

---

tailoff/js/components/glide.component.ts

Fixes #137
Added smooth opacity changes to the slider. No more weird jumping of cards. 
Also added some extra data attributes to controle the slider from the HTML.

Change opacity jump in carrousel.

---

tailoff/js/components/leaflet.component.ts

Change Nominatim url to make Leaflet maps work again

---

tailoff/js/components/dropdown.component.ts
templates/_site/_layout.twig
templates/jsPlugins/dropdown.twig
templates/jsPlugins/overview.twig

Fixes #98
Changed the position code to @floating-ui/dom
And made a plugin example page. 
Also alterd the code a bit to make the A11y beter.

Dropdown position not always correct when displayed in footer

---

tailoff/js/components/ajaxSearch.component.ts
templates/jsPlugins/ajaxsearch.twig

Optimize ajaxsearch component

---

tailoff/js/components/formOptionalBlocks.component.ts
templates/jsPlugins/formValidation.twig

Make nested optional fields work with the validator.

---

templates/_site/_snippet/_content/_blocks/_callToAction.twig
templates/_site/_snippet/_content/_blocks/_image.twig
templates/_site/_snippet/_content/_blocks/_slider.twig
templates/_site/_snippet/_content/_defaultHeader.twig
templates/_site/_snippet/_content/_hero.twig
templates/_site/_snippet/_item/_card.twig
templates/jsPlugins/slider.twig

Refine the webp src condition

---

templates/_site/_snippet/_content/_blocks/_image.twig

Fixes #119
This was already fixed, apparently. I just set the full width image back to full width, to make the sizes consistent.

Improve _image.twig template

---

templates/_site/_layout.twig

Fix typo in my previous PR.

---

tailoff/js/components/toggle.component.ts

Update the toggle component to make the expended by default work properly

---

config/project/entryTypes/accessibilityStatement--c113b5bd-7822-4e56-933c-ed2a6ae65111.yaml
config/project/project.yaml
config/project/sections/accessibilityStatement--99a435d2-9c12-4ef6-8b3b-2a9915d4216b.yaml
config/project/superTableBlockTypes/ed516703-9411-446f-8ce9-d66e9c48839a.yaml
config/project/users/groups/contentManagers--3196b984-5af4-44dd-a6db-ac2c8f7924d9.yaml

Add new Single for Accessibility Statement

---

config/project/project.yaml
config/project/sections/news--c576870d-abd8-46aa-8fe5-cdd12c40dfa8.yaml

Set default status of News entries to disabled

---

googlefonts.js
package.json
postcss.config.js
yarn.lock

Update to vite 5

---

modules/statik/src/Statik.php
modules/statik/src/variables/StatikVariable.php
modules/statik/src/web/twig/HyperExtension.php
modules/statik/src/web/twig/PaginateExtension.php
modules/statik/src/web/twig/StatikExtension.php
templates/_site/_layout.twig
templates/_site/_news/_index.twig
templates/_site/_snippet/_content/_blocks/_callToAction.twig
templates/_site/_snippet/_content/_blocks/_form.twig
templates/_site/_snippet/_content/_blocks/_overview.twig
templates/_site/_snippet/_content/_blocks/_quote.twig
templates/_site/_snippet/_content/_blocks/_textImage.twig
templates/_site/_snippet/_content/_blocks/_textTwoColumns.twig
templates/_site/_snippet/_content/_blocks/_textVideo.twig
templates/_site/_snippet/_content/_hero.twig
templates/jsPlugins/ajaxPaging.twig
templates/jsPlugins/filter.twig
templates/jsPlugins/filterButton.twig

Refactor standard StatikVariable functions into Twig Extensions so StatikVariable is clean for custom project code

---

modules/statik/src/Statik.php
modules/statik/src/web/twig/ValidateInputExtension.php
templates/_site/_searchResults.twig
templates/jsPlugins/filter.twig

@HannahDeWachter 
Potentiele fix voor jouw vraag. Denk jij dat dit een sluitende oplossing is?

#145 implement twig tests to validate if a query or id is valid

---

composer.json
composer.lock
config/seo-fields.php

Includes:
- SEO Fields update to 4.0.2
- Added plugin config file with current defaults

SEO update

---

composer.json
composer.lock
modules/statik/src/web/twig/StatikExtension.php
templates/_site/_layout.twig

fixes #239 
otherwise cookie banner html gets indexed and ruins google results

#239: hide cookiebanner for search engines

---

.github/workflows/demo.yml
.github/workflows/main.yml
.github/workflows/staging.yml
yarn.lock

Fixed github action yaml files for deploy

Fix github action for deploy (#263)

---

tailoff/js/components/formOptionalBlocks.component.ts
tailoff/js/plugins/validation/passwordStrength.plugin.ts
templates/jsPlugins/formValidation.twig

Fixes #245
I also made some small cleanup touches.

Add changes to the optional form plugin for optional required state.

---

tailoff/js/components/autocomplete.component.ts
tailoff/js/components/formie.component.ts
tailoff/js/utils/domHelper.ts

Add multiselect to formie component

---

modules/statik/src/web/twig/HyphenateExtension.php

Add soft hyphens to the base install

---

tailoff/css/site/components/form.css

Optimize Formie Stencil

---

config/project/matrixBlockTypes/callToAction--7b5ab248-6255-4b42-88bc-80c1dee62b20.yaml
config/project/matrixBlockTypes/customTable--f2d33237-c7de-4590-9683-7efe6594ebbd.yaml
config/project/matrixBlockTypes/form--f3211a4e-d5f8-4514-a372-c5b8cfc2c44a.yaml
config/project/matrixBlockTypes/image--0396f80c-a192-4beb-a6e7-075075cf0f70.yaml
config/project/matrixBlockTypes/overview--24bd0074-b53d-404d-9285-a0be9f26bbd4.yaml
config/project/matrixBlockTypes/quote--7256a782-20ff-4771-9d85-ed3f49e13ef4.yaml
config/project/matrixBlockTypes/textImage--d86336d6-7efa-44f9-9a10-8619c79beeca.yaml
config/project/matrixBlockTypes/textTwoColumns--1e4267e1-8d5f-4312-8458-86b19bc17d74.yaml
config/project/matrixBlockTypes/textVideo--95920915-f806-4fbc-9c22-979ec9085fe8.yaml
config/project/matrixBlockTypes/video--209777db-293c-48b6-9897-1fe97b278510.yaml
config/project/project.yaml
modules/statik/src/assetbundles/Statik/dist/css/Statik.css
tailoff/css/site/base/base.css
tailoff/js/components/videoToggle.component.ts
templates/_site/_searchResults.twig
templates/_site/_snippet/_content/_blocks/_callToAction.twig
templates/_site/_snippet/_content/_blocks/_customTable.twig
templates/_site/_snippet/_content/_blocks/_textImage.twig
templates/_site/_snippet/_content/_blocks/_textTwoColumns.twig
templates/_site/_snippet/_content/_blocks/_textVideo.twig
templates/_site/_snippet/_content/_blocks/_video.twig
templates/_site/_snippet/_content/_intro.twig
templates/_site/_snippet/_item/_card.twig

Add "Video description" field to both video blocks

---

deploy.php

Added task after deploy to reload phpfpm on a **Combell** server.
After deployer finishes the deploy to a new version, phpfpm keeps code in memory.
In some cases this will lead to old parts of code being run on top of newer deployed parts.
reloading phpfpm fixes this.

Reload phpfpm after deploy and symlink of new version.

---

templates/_site/_layout.twig

Don’t index on statik.be domains

---

composer.json
composer.lock
config/craft-sentry.php
config/project/project.yaml

Install Sentry plugin & add config file

---

templates/_site/_snippet/_content/_blocks/_textVideo.twig
templates/_site/_snippet/_content/_blocks/_video.twig

Use responsive images / sourceset for Youtube thumbnails?

---

templates/_site/_snippet/_global/_footer.twig

Add link to Accessibility Statement in footer

---

templates/_site/_snippet/_content/_blocks/_image.twig
templates/_site/_snippet/_content/_blocks/_textImage.twig
templates/_site/_snippet/_content/_defaultHeader.twig

Fix issue: https://github.com/statikbe/craft/issues/282
'-' replaced by '©'

282: replace - with © in image copyright

---

templates/_site/_layout.twig

Put the cookie banner code at the bottom?

---

tailoff/js/components/formOptionalBlocks.component.ts

alter formOptionalBlocks with the commit from CCVWEB-185

---

tailoff/js/components/filter.component.ts

Add nearest to filter component.

---

modules/statik/src/console/controllers/SetupController.php

Fixed error in SetupController (#352)

---

tailoff/js/components/modal.component.ts

Add dynamic change options to modal.

---

composer.json
composer.lock

BUG: update knock knock to fix setup/welcome bug

---

config/knock-knock.php
templates/_knock-knock.twig

[Feature] improve design custom knock knock template

---

config/project/entryTypes/callToAction--7b5ab248-6255-4b42-88bc-80c1dee62b20.yaml
config/project/entryTypes/form--f3211a4e-d5f8-4514-a372-c5b8cfc2c44a.yaml
config/project/entryTypes/textImage--d86336d6-7efa-44f9-9a10-8619c79beeca.yaml
config/project/entryTypes/textTwoColumns--1e4267e1-8d5f-4312-8458-86b19bc17d74.yaml
config/project/entryTypes/textVideo--95920915-f806-4fbc-9c22-979ec9085fe8.yaml
config/project/fields/cta--71d59fcf-f766-4db1-a6fe-87bf1ce1b1ba.yaml
config/project/fields/ctas--f936530d-29a5-4460-9ccd-b586bfb25329.yaml
config/project/project.yaml

Improve fields

---

composer.json
composer.lock
config/craft-sentry.php

[FEATURE] Update sentry plugin and configure ignored exceptions

---

tailoff/js/components/filter.component.ts

Add pagination back and forward fix to the filter component.

---

tailoff/css/site/base/base.css

Add text-balance property to headings

---

config/general.php

Add preserve img color settings to general config

---

config/image-optimize.php

fixes #416 
Upscaling images is extremely slow on some servers

[CONFIG] update optimze image settings

---

config/app.php

Added project specific log target

---

config/general.php

[CONFIG] #431 add option value

---

tailoff/js/components/chip.component.ts

Add the chip-cleared event to the chip component

---

templates/_site/_account/_passwordSet.twig

Fix password strength indiciator not being shown on page

---

tailoff/js/components/autocomplete.component.ts

Add the option to take the class from the options in the autocomplete.
