statikbe/craft

webpack.config.js
Makes Webpack play nice with Windows-style paths. According to the solution found [here](https://github.com/webpack/webpack/issues/2073).
=> Adapt webpack regex for Windows

tailoff/js/components/tooltip.component.ts
Added an extra condition so when there is only a [data-tippy-template] attribute on the page, the tooltip component gets fired as well.
=> Add conditional for tippy template attribute

modules/statik/src/variables/StatikVariable.php, templates/_site/_news/_index.twig, templates/jsPlugins/ajaxPaging.twig, templates/jsPlugins/filter.twig, templates/jsPlugins/filterButton.twig
De paginate function zou beter een consistent return type hebben om mee te werken. Op deze manier kan je het resultaat ook in een variabele steken moest je er nog iets van manipulatie op moeten doen.
=> [StatikVariable] paginate function should return consistent return type

post-deploy-craft3.sh
Ik was aan het lezen over de best practices ivm het clearen van caches bij het deployen omdat we bij een project even wat rare resultaten kregen na een deploy en het probleem foutieve caches bleek te zijn.
Op deze pagina van craftcms zelf raden ze aan om bij elke deploy de caches te clearen
https://craftcms.com/knowledge-base/deployment-best-practices
Ik vond ook dit advies terug op de stack overflow van craft dat ik heel duidelijk vond. 
https://craftcms.stackexchange.com/a/39557
=> Add clear-caches to post-deploy-craft3 script.

tailoff/js/components/autocomplete.component.ts
Fixes #112
Makes the search in the autocomplete ignore accents for an easier search.
=> Change the getOptions function in the autocomplete component to this.

composer.json, composer.lock, templates/_site/_snippet/_content/_blocks/_textVideo.twig, templates/_site/_snippet/_content/_blocks/_video.twig
In watwec wou de klant vimeo video's gebruiken die aan hun organisation account hangen. Daardoor krijgen die een ander soort URL dat de video-parser niet kon parsen. 
Deze nieuwe urls kopieren zij uit de backend als 'https://vimeo.com/834728934/3fb1f201e9' en om te embedden moeten dit worden 'https://player.vimeo.com/video/834728934?h=3fb1f201e9' 
Deze pull request voegt aan de base install toe dat wij out of the box al deze video format supporten.
=> Fix for vimeo urls that are formatted like https://vimeo.com/834728934/3fb1f201e9

templates/_site/_layout.twig
Add entry.canSave(currentUser) check to edit pencil to avoid showing it when the page is not available to edit for currentUser
=> More robust check if we can show edit pencil

.ddev/config.yaml
don't upload user uploads and node modules
@KarelJanVanHaute 
This commit excludes the public/files folder and node modules folder from being synced my mutagen. This should speed up mutagen sync very much and shouldn't hurt performance because these files should not be changing often in development. Could you try out if it works well for you?
=> [Local development] performance tweaks in ddev config

bitbucket-pipelines.yml, composer.json
Sync PHP version to match default DDEV configuration so deploy and combell server setting work out of box
If  you start a new project right now because of the the DDEV configuration the minimum requirement of PHP packages will be PHP 8.2. By setting the minimum PHP requirement in bitbucket container and composer deploying will work right out of the box.
=> Fix: Sync PHP version

deploy.php
=> Fix: translations dir should be shared over deploys otherwise translate settings dissapear

modules/statik/src/Statik.php
Cleaning up unmaintained code snippets.
=> Fix: remove code that has been in comment for more than a year

.github/workflows/ci.yml, modules/statik/src/Statik.php, modules/statik/src/console/controllers/SetupController.php, modules/statik/src/web/twig/HyperExtension.php, modules/statik/src/web/twig/HyphenateExtension.php, modules/statik/src/web/twig/PaginateExtension.php, modules/statik/src/web/twig/StatikExtension.php, modules/statik/src/web/twig/ValidateInputExtension.php
This PR adds an automatic code styling check that will run for any new PR, to ensure that our code all follows the same style & conventions.
The check is defined for our organisation (https://github.com/statikbe/.github/tree/main/.github/workflows), so we can easily expand and update these checks outside of the repository.
You can run these check locally as well, with the command `(ddev) composer check-cs` to just check your code, or `(ddev) composer fix-cs` to have any errors fixed automatically.
=> ECS checks on PR

prettier.config.cjs, templates/_site/_snippet/_content/_blocks/_image.twig
Fixes #315
Changed the default a-tag to a button. This makes more sense, considering it's a action and not a navigation.
=> Improve the image popup experience A11y wise

modules/statik/src/web/twig/ValidateInputExtension.php
Fix issue: https://github.com/statikbe/craft/issues/322
Updated regex to allow spaces in a search term.
=> 322: fixed regex in the validateInputExtension file

package.json, tailoff/js/components/ckeEditor.component.ts, tailoff/js/site.ts, yarn.lock
Fixes #351
This adds the ability to use CKEditor in the frontend.
=> Add ckeEditor component

modules/statik/src/assetbundles/anchorlinkfield/dist/js/AnchorLink.js, modules/statik/src/controllers/SlugifyController.php
If uri part didn't get explicitely encoded browsers would struggle with the ? part. 
fixes #421
=> [BUG]: anchor field does not work with question mark

.env.example, config/project/formie/stencils/contactForm_EN--ac589bc4-75c7-4f97-b57b-61025fc0643f.yaml, config/project/formie/stencils/contactForm_FR--68c6a8e9-4391-473a-8b44-293bb38d1f32.yaml, config/project/formie/stencils/contactForm_NL--b1ca80f0-4eed-4f99-bebc-bca6c694cb00.yaml, config/project/project.yaml, modules/statik/src/console/controllers/SetupController.php
Set recaptcha on by default in formie settings and stencils.
Setup command now asks for recaptcha key on initial setup to add it to the .env file. 
We want to help developers make sane defaults
=> [CONFIG] #422 add recaptcha default on forms

tailoff/js/plugins/modal/ajax.plugin.ts, tailoff/js/site.ts
=> Add Ajax modal plugin to baseinstall

tailoff/css/site/components/table.css, tailoff/js/components/table.component.ts
=> Add optimisation to the custom table

templates/_site/_contact.twig, templates/_site/_layout.twig, templates/_site/_snippet/_content/_blocks/_callToAction.twig, templates/_site/_snippet/_content/_blocks/_customTable.twig, templates/_site/_snippet/_content/_blocks/_quote.twig, templates/_site/_snippet/_content/_blocks/_textImage.twig, templates/_site/_snippet/_content/_blocks/_textTwoColumns.twig, templates/_site/_snippet/_content/_blocks/_textVideo.twig
Removed enkode_emails on layout.twig and only add it where it makes sense fixes #420 
Does weird things with forms where you can edit your email afterwards like an account flow
=> [BUG] #420 remove enkode_emails over entire content

templates/_site/_snippet/_global/_footer.twig
=> Add The Kind Kids in the footer

bitbucket-pipelines.yml, deploy.php
using SSH multiplexing and some better options should make the deploy more reliable also for KUL projects and faster.
fixes #453
=> [Devops] Improved deployer settings and steps
